# Generated by Django 5.0.7 on 2024-07-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("facilities", models.TextField()),
                ("charge_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_info", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
