# Generated by Django 5.0.7 on 2024-08-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0002_country_rename_contact_info_venue_contact_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="name",
            field=models.CharField(default="default name", max_length=100),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(default="001", max_length=100),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentals.event"
                    ),
                ),
                (
                    "ticket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentals.ticket"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepartmentPermission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("permissions", models.CharField(max_length=255)),
                ("module", models.CharField(max_length=255)),
                ("urls", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="rentals.department",
                    ),
                ),
            ],
        ),
    ]
