# Generated by Django 5.0.7 on 2024-08-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0003_ticket_name_transaction_reference_id_booking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference_id",
            field=models.CharField(max_length=100),
        ),
    ]
