# Generated by Django 5.0.7 on 2024-07-26 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessControl",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "access_level",
                    models.CharField(
                        choices=[("full", "Full"), ("restricted", "Restricted")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rentals.event"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
