# Generated by Django 5.0.7 on 2024-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0005_alter_ticket_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name="venue",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
