# Generated by Django 5.0.7 on 2024-08-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0006_event_file_venue_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="events/files/"),
        ),
        migrations.AlterField(
            model_name="venue",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="venues/files/"),
        ),
    ]
