# Generated by Django 5.0.7 on 2024-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0007_alter_event_file_alter_venue_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="file",
            field=models.FileField(default="text.txt", upload_to="events/files/"),
        ),
    ]
