# Generated by Django 5.0.7 on 2024-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0008_alter_event_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="events/files/"),
        ),
    ]
