# Generated by Django 5.0.7 on 2024-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0009_alter_event_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
