# Generated by Django 5.0.7 on 2024-08-21 05:40

import rentals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0010_venue_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=rentals.models.Event.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="venue",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=rentals.models.Venue.upload_to
            ),
        ),
    ]
